name: CI for eProsima xTypes

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - 'main'
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '!**/CMakeLists.txt'
  pull_request:
    branches:
      - 'master'
      - 'main'
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '!**/CMakeLists.txt'

jobs:
  xtypes_CI:
    uses: ./.github/workflows/reusable-github-ci.yml
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip-ci') }}
    with:
      label: "Running-CI"
      os: "[\"ubuntu-latest\",\"windows-latest\",\"macos-latest\"]"
      config: "[\"RelWithDebInfo\"]"
      vs_toolset: "[\"v143\",\"v142\"]"
      cmake_args: "[\"-DXTYPES_EXCEPTIONS=ON\",\"-DCMAKE_CXX_STANDARD=20\"]"
