name: CI for eProsima xTypes

on:
  push:
    branches:
      - bugfix/parser_annotations
    pull_request:
      branches:
        - '**'

jobs:
  xtypes_CI:
    runs-on: ubuntu-20.04
    container: ubuntu:focal

    steps:

      - name: Download required dependencies
        run: |
          apt update
          DEBIAN_FRONTEND=noninteractive apt install -y cmake gcc g++ git valgrind

      - uses: actions/checkout@v2
        with:
          path: src/xtypes
          submodules: true

      - name: Install colcon
        run: |
          apt install -y python3-pip
          pip3 install -U colcon-common-extensions

      - name: Build
        run: |
          colcon build --cmake-args "-DXTYPES_BUILD_TESTS=ON -DXTYPES_BUILD_EXAMPLES=ON -DXTYPES_EXCEPTIONS=ON -DMEMORYCHECK_COMMAND_OPTIONS=-q --tool=memcheck --leak-check=yes --show-reachable=yes --num-callers=50 --xml=yes --xml-file=test_%p_memcheck.xml"

      - name: Test
        run: |
          . install/local_setup.sh && ctest -VV -D ExperimentalTest --no-compress-output

      - name: Valgrind
        run: |
          . install/local_setup.sh && ctest -VV -D ExperimentalMemCheck --no-compress-output -LE NoMemoryCheck
